server:
  port: 8000

spring:
  zookeeper-address:
    register: register:2181
    master-meta: master-meta-db:2182
    slave-meta: slave-meta-db:2183
  task:
    execution:
      pool:
        core-size: 10
        max-size: 20
        queue-capacity: 1000
